eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: eureka-client
  cloud:
    config:
      label: master
      profile: local
      discovery:
        enabled: true
        serviceId: config-server
#      uri: http://localhost:8888/
  rabbitmq:
    host: localhost
    port: 5672
    username: springcloud
    password: 123456

server:
  port: 8882


management:
  security:
    enabled: false